######################################################################
##
## Filename: top_fpga_tb.udo
## Created on: Fri Dec 08 3:57:26 AM Eastern Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################

add wave -position insertpoint sim:/top_fpga_tb/uut/*
add wave -position insertpoint sim:/top_fpga_tb/uut/U7/*