######################################################################
##
## Filename: top_fpga.udo
## Created on: Thu Dec 07 8:14:20 PM Eastern Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
add wave *

